=== Berk1034/Web-Technologies/Coffee-MACHINE-WEB/data/UserProfiles.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.example.com/UserProfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="Surname" type="xs:string"/>
  <xs:element name="Age" type="xs:short"/>
  <xs:element name="CreationDate" type="xs:long"/>
  <xs:element name="UserProfile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="user:Name" xmlns:user="http://www.example.com/UserProfiles"/>
        <xs:element ref="user:Surname" xmlns:user="http://www.example.com/UserProfiles"/>
        <xs:element ref="user:Age" xmlns:user="http://www.example.com/UserProfiles"/>
        <xs:element ref="user:CreationDate" xmlns:user="http://www.example.com/UserProfiles"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="UserProfiles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="user:UserProfile" maxOccurs="unbounded" minOccurs="0" xmlns:user="http://www.example.com/UserProfiles"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Berk1034/Web-Technologies/Coffee-MACHINE-WEB/data/UserProfiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<UserProfiles xmlns:tns="http://www.w3.org/2001/XMLSchema-instance"
	      xmlns="http://www.example.com/UserProfiles"
		tns:schemaLocation="http://www.example.com/UserProfiles UserProfiles.xsd">
  <UserProfile>
    <Name>Berk</Name>
    <Surname>Oops</Surname>
    <Age>1034</Age>
    <CreationDate>1574240745049</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Berk</Name>
    <Surname>Oops</Surname>
    <Age>1034</Age>
    <CreationDate>1574240745049</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Constantin</Name>
    <Surname>Hitov</Surname>
    <Age>19</Age>
    <CreationDate>1574240977063</CreationDate>
  </UserProfile>
</UserProfiles>

=== Berk1034/Web-Technologies/Coffee-MACHINE-WEB/data/UserProfiles_7Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<UserProfiles xmlns:tns="http://www.w3.org/2001/XMLSchema-instance"
	      xmlns="http://www.example.com/UserProfiles"
		tns:schemaLocation="http://www.example.com/UserProfiles UserProfiles.xsd">
  <UserProfile>
    <Name>Berk</Name>
    <Surname>Oops</Surname>
    <Age>1034</Age>
    <CreationDate>1574240745049</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Constantin</Name>
    <Surname>Hitov</Surname>
    <Age>20</Age>
    <CreationDate>1574240977063</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Poppy</Name>
    <Surname>Harlow</Surname>
    <Age>18</Age>
    <CreationDate>1575748904534</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Peepee</Name>
    <Surname>Poopoo</Surname>
    <Age>20</Age>
    <CreationDate>1575749141902</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Gloria</Name>
    <Surname>Boogue</Surname>
    <Age>30</Age>
    <CreationDate>1575748994304</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Bob</Name>
    <Surname>Just call me BOB</Surname>
    <Age>20</Age>
    <CreationDate>1575749994304</CreationDate>
  </UserProfile>
  <UserProfile>
    <Name>Hope</Name>
    <Surname>Nope</Surname>
    <Age>100</Age>
    <CreationDate>1575750994304</CreationDate>
  </UserProfile>
</UserProfiles>
